[profile.default]
solc = "0.8.30"
src = "src"
out = "out"
libs = ["lib", "dependencies"]
evm_version = "cancun"
auto_detect_solc = false
ffi = true
optimizer = true
optimizer-runs = 200
via_ir = true

# File permissions for deployment saves
fs_permissions = [
    { access = "read-write", path = "./deployments" }
]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.0.1"
"@openzeppelin-contracts-upgradeable" = "5.0.1"

