[profile.default]
solc = "0.8.30"
src = "src"
out = "out"
libs = ["lib", "dependencies", "node_modules"]
evm_version = "cancun"
auto_detect_solc = false
ffi = true
optimizer = true
optimizer-runs = 200
via_ir = true

# Build info and storage layout for upgrades validation
build_info = true
extra_output = ["storageLayout"]

# File permissions for deployment saves and OpenZeppelin Foundry API
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" }
]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.0.1"
"@openzeppelin-contracts-upgradeable" = "5.0.1"

