[profile.default]
solc = "0.8.30"
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
auto_detect_solc = false
ffi = true
optimizer = true
optimizer-runs = 200
via_ir = true


# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/"
]

# File permissions for deployment saves
fs_permissions = [
    { access = "read-write", path = "./deployments" }
]
